# Generated by Django 5.1.6 on 2025-02-22 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='-', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница'), ('Суббота', 'Суббота')], max_length=20, unique=True)),
                ('group_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_key', to='app.group')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.CharField(choices=[('Математика', 'Математика'), ('Физика', 'Физика'), ('Русский язык', 'Русский язык'), ('Белорусский язык', 'Белорусский язык'), ('Русская литература', 'Русская литература'), ('Бел Литература', 'Беларусская литература'), ('Английский язык', 'Английский язык'), ('Биология', 'Биология'), ('Химия', 'Химия'), ('География', 'География'), ('Сольфеджио', 'Сольфеджио'), ('ПДД', 'ПДД'), ('Эл. Теория Музыки', 'Эл. Теория музыки'), ('Хоровой класс', 'Хоровой класс'), ('Хороведение', 'Хороведение'), ('Физ-ра', 'Физ-ра'), ('Информатика', 'Информатика'), ('История', 'История'), ('Обществоведение', 'Обществоведение'), ('Классный час', 'Классный час'), ('---', 'Ничего'), ('Другое', 'Другое')], max_length=20)),
                ('lesson_starts_time', models.TimeField(choices=[('8:30-9:15', '8:30-9:15'), ('9:25-10:10', '9:25-10:10'), ('10:20-11:05', '10:20-11:05'), ('11:15-12:00', '11:15-12:00'), ('12:20-13:05', '12:20-13:05'), ('13:15-14:00', '13:15-14:00'), ('14:10-14:55', '14:10-14:55'), ('15:05-15:50', '15:05-15:50'), ('16:00-16:45', '16:00-16:45'), ('16:55-17:40', '16:55-17:40'), ('17:50-18:35', '17:50-18:35'), ('18:45-19:30', '18:45-19:30')])),
                ('lesson_ends_time', models.TimeField(choices=[('8:30-9:15', '8:30-9:15'), ('9:25-10:10', '9:25-10:10'), ('10:20-11:05', '10:20-11:05'), ('11:15-12:00', '11:15-12:00'), ('12:20-13:05', '12:20-13:05'), ('13:15-14:00', '13:15-14:00'), ('14:10-14:55', '14:10-14:55'), ('15:05-15:50', '15:05-15:50'), ('16:00-16:45', '16:00-16:45'), ('16:55-17:40', '16:55-17:40'), ('17:50-18:35', '17:50-18:35'), ('18:45-19:30', '18:45-19:30')])),
                ('classroom', models.CharField(max_length=10)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_key', to='app.day')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_key', to='app.teacher')),
            ],
        ),
    ]
