# Generated by Django 5.1.6 on 2025-02-22 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='lesson',
            new_name='subject',
        ),
    ]
