# Generated by Django 5.1.6 on 2025-02-22 21:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_lesson_lesson_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_ends_time',
            field=models.TimeField(choices=[(datetime.time(8, 30), '8:30'), (datetime.time(9, 25), '9:25'), (datetime.time(10, 20), '10:20'), (datetime.time(11, 15), '11:15'), (datetime.time(12, 20), '12:20'), (datetime.time(13, 15), '13:15'), (datetime.time(14, 10), '14:10'), (datetime.time(15, 5), '15:05'), (datetime.time(16, 0), '16:00'), (datetime.time(16, 55), '16:55'), (datetime.time(17, 50), '17:50'), (datetime.time(18, 45), '18:45')]),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_starts_time',
            field=models.TimeField(choices=[(datetime.time(8, 30), '8:30'), (datetime.time(9, 25), '9:25'), (datetime.time(10, 20), '10:20'), (datetime.time(11, 15), '11:15'), (datetime.time(12, 20), '12:20'), (datetime.time(13, 15), '13:15'), (datetime.time(14, 10), '14:10'), (datetime.time(15, 5), '15:05'), (datetime.time(16, 0), '16:00'), (datetime.time(16, 55), '16:55'), (datetime.time(17, 50), '17:50'), (datetime.time(18, 45), '18:45')]),
        ),
    ]
