# Generated by Django 5.1.6 on 2025-02-22 21:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_lesson_lesson_ends_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_ends_time',
            field=models.TimeField(choices=[(datetime.time(9, 15), '9:15'), (datetime.time(10, 10), '10:10'), (datetime.time(11, 5), '11:05'), (datetime.time(12, 0), '12:00'), (datetime.time(13, 5), '13:05'), (datetime.time(14, 0), '14:00'), (datetime.time(14, 55), '14:55'), (datetime.time(15, 50), '15:50'), (datetime.time(16, 45), '16:45'), (datetime.time(17, 40), '17:40'), (datetime.time(18, 35), '18:35'), (datetime.time(19, 30), '19:30')]),
        ),
    ]
