# Generated by Django 5.1.6 on 2025-02-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_lesson_lesson_ends_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_ends_time',
            field=models.TimeField(editable=False),
        ),
    ]
